apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: s2i-express
    name: s2i-express
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: s2i-express
    name: s2i-express
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: s2i-express:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/patricksimonian/s2i-express.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:10
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: jQn4R1MESjFMuNDn3hdj
      type: GitHub
    - generic:
        secret: iWwiZy12Z_LRgFVcwrN2
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
